"""create wiki_chunk table

Revision ID: 2ac2f41edf9c
Revises:
Create Date: 2025-12-26 23:16:12.765521

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ac2f41edf9c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wiki_chunk",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("wiki_page_id", sa.String(length=100), nullable=False),
        sa.Column("article_title", sa.String(length=500), nullable=False),
        sa.Column("section_path", sa.String(length=1000), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wiki_chunk_article_title"), "wiki_chunk", ["article_title"], unique=False
    )
    op.create_index(
        op.f("ix_wiki_chunk_wiki_page_id"), "wiki_chunk", ["wiki_page_id"], unique=False
    )

    # Create expression indexes for JSON fields (SQLite)
    # These indexes use json_extract to enable efficient querying of metadata fields
    op.execute("""
        CREATE INDEX ix_wiki_chunk_faction
        ON wiki_chunk(json_extract(metadata_json, '$.faction'))
    """)
    op.execute("""
        CREATE INDEX ix_wiki_chunk_era
        ON wiki_chunk(json_extract(metadata_json, '$.era'))
    """)
    op.execute("""
        CREATE INDEX ix_wiki_chunk_spoiler_flag
        ON wiki_chunk(json_extract(metadata_json, '$.spoiler_flag'))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop expression indexes for JSON fields
    op.execute("DROP INDEX IF EXISTS ix_wiki_chunk_spoiler_flag")
    op.execute("DROP INDEX IF EXISTS ix_wiki_chunk_era")
    op.execute("DROP INDEX IF EXISTS ix_wiki_chunk_faction")

    op.drop_index(op.f("ix_wiki_chunk_wiki_page_id"), table_name="wiki_chunk")
    op.drop_index(op.f("ix_wiki_chunk_article_title"), table_name="wiki_chunk")
    op.drop_table("wiki_chunk")
    # ### end Alembic commands ###
