"""Unit tests for WikiChunk model."""

from datetime import UTC, datetime

from src.models.wiki_chunk import WikiChunk


class TestWikiChunk:
    """Test suite for WikiChunk model."""

    def test_wiki_chunk_creation(self) -> None:
        """Test creating a WikiChunk instance."""
        chunk = WikiChunk(
            wiki_page_id="123",
            article_title="Test Article",
            section_path="Introduction > History",
            chunk_text="This is a test chunk of text.",
            chunk_index=0,
            metadata_json={
                "faction": "Space Marines",
                "era": "Horus Heresy",
                "spoiler_flag": False,
                "content_type": "lore",
                "character_names": ["Horus", "Emperor"],
                "links": [],
                "source_books": [],
            },
        )

        assert chunk.wiki_page_id == "123"
        assert chunk.article_title == "Test Article"
        assert chunk.section_path == "Introduction > History"
        assert chunk.chunk_text == "This is a test chunk of text."
        assert chunk.chunk_index == 0
        assert chunk.metadata_json["faction"] == "Space Marines"

    def test_wiki_chunk_deterministic_id_generation(self) -> None:
        """Test that WikiChunk generates a deterministic ID from wiki_page_id and chunk_index."""
        chunk = WikiChunk(
            wiki_page_id="123",
            article_title="Test Article",
            section_path="Section",
            chunk_text="Text",
            chunk_index=0,
            metadata_json={},
        )

        # Should have an id (generated by default)
        assert chunk.id is not None
        # Should be in deterministic format: {wiki_page_id}_{chunk_index}
        assert chunk.id == "123_0"

        # Test with different values
        chunk2 = WikiChunk(
            wiki_page_id="456",
            article_title="Another Article",
            section_path="Section",
            chunk_text="Text",
            chunk_index=5,
            metadata_json={},
        )
        assert chunk2.id == "456_5"

    def test_wiki_chunk_metadata_json_accepts_dict(self) -> None:
        """Test that metadata_json field accepts dictionary."""
        metadata = {
            "faction": "Tyranids",
            "subfaction": "Hive Fleet Leviathan",
            "character_names": ["Hive Tyrant"],
            "era": None,
            "spoiler_flag": True,
            "content_type": "military",
            "links": ["Link1", "Link2"],
            "source_books": ["Codex: Tyranids"],
        }

        chunk = WikiChunk(
            wiki_page_id="456",
            article_title="Tyranids",
            section_path="Main",
            chunk_text="Tyranid text",
            chunk_index=0,
            metadata_json=metadata,
        )

        assert chunk.metadata_json == metadata
        assert chunk.metadata_json["faction"] == "Tyranids"
        assert chunk.metadata_json["subfaction"] == "Hive Fleet Leviathan"
        assert chunk.metadata_json["character_names"] == ["Hive Tyrant"]
        assert chunk.metadata_json["spoiler_flag"] is True

    def test_wiki_chunk_created_at_auto_populated(self) -> None:
        """Test that created_at is automatically populated."""
        before = datetime.now(UTC)

        chunk = WikiChunk(
            wiki_page_id="789",
            article_title="Auto Timestamp Test",
            section_path="Test",
            chunk_text="Test",
            chunk_index=0,
            metadata_json={},
        )

        after = datetime.now(UTC)

        assert chunk.created_at is not None
        assert before <= chunk.created_at <= after

    def test_wiki_chunk_updated_at_auto_populated(self) -> None:
        """Test that updated_at is automatically populated."""
        before = datetime.now(UTC)

        chunk = WikiChunk(
            wiki_page_id="101",
            article_title="Update Timestamp Test",
            section_path="Test",
            chunk_text="Test",
            chunk_index=0,
            metadata_json={},
        )

        after = datetime.now(UTC)

        assert chunk.updated_at is not None
        assert before <= chunk.updated_at <= after

    def test_wiki_chunk_repr(self) -> None:
        """Test string representation of WikiChunk."""
        chunk = WikiChunk(
            id="test-uuid-123",
            wiki_page_id="999",
            article_title="Repr Test Article",
            section_path="Test",
            chunk_text="Test",
            chunk_index=0,
            metadata_json={},
        )

        repr_str = repr(chunk)
        assert "WikiChunk" in repr_str
        assert "test-uuid-123" in repr_str
        assert "Repr Test Article" in repr_str

    def test_wiki_chunk_default_metadata_json(self) -> None:
        """Test that metadata_json defaults to empty dict."""
        chunk = WikiChunk(
            wiki_page_id="202",
            article_title="Default Metadata Test",
            section_path="Test",
            chunk_text="Test",
            chunk_index=0,
        )

        assert chunk.metadata_json == {}
        assert isinstance(chunk.metadata_json, dict)
